import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const auth = req.headers.get("Authorization");
    if (!auth) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
    const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      global: { headers: { Authorization: auth } },
    });

    const { data: userData, error: userErr } = await supabase.auth.getUser();
    if (userErr || !userData.user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: roleRow } = await supabase
      .from("user_roles").select("role").eq("user_id", userData.user.id).eq("role", "teacher").maybeSingle();
    if (!roleRow) {
      return new Response(JSON.stringify({ error: "Teachers only" }), {
        status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { essay_id } = await req.json();
    if (!essay_id) {
      return new Response(JSON.stringify({ error: "essay_id required" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: essay, error: essayErr } = await supabase
      .from("essays").select("id, content").eq("id", essay_id).maybeSingle();
    if (essayErr || !essay) {
      return new Response(JSON.stringify({ error: "Essay not found" }), {
        status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (!essay.content || essay.content.trim().length < 20) {
      return new Response(JSON.stringify({ error: "Essay too short to analyze" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const aiResp = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${LOVABLE_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          {
            role: "system",
            content:
              "You are an expert AI-text detector. Estimate the probability that the given text was generated by an AI model rather than written by a student. Consider tell-tale signs: overly uniform sentence rhythm, generic transitions ('Moreover', 'Furthermore', 'In conclusion'), polished but vague claims, lack of personal voice, perfect grammar without errors typical of student writing. Respond ONLY with strict JSON: {\"probability\": <integer 0-100>, \"reasoning\": \"<one short sentence>\"}. No prose outside JSON.",
          },
          { role: "user", content: `Analyze this student essay:\n\n${essay.content.slice(0, 8000)}` },
        ],
        response_format: { type: "json_object" },
      }),
    });

    if (!aiResp.ok) {
      const t = await aiResp.text();
      console.error("AI gateway error", aiResp.status, t);
      return new Response(JSON.stringify({ error: "AI service error" }), {
        status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const aiJson = await aiResp.json();
    const text = aiJson.choices?.[0]?.message?.content ?? "{}";
    let probability = 0;
    let reasoning = "";
    try {
      const parsed = JSON.parse(text);
      probability = Math.max(0, Math.min(100, Math.round(Number(parsed.probability) || 0)));
      reasoning = String(parsed.reasoning || "");
    } catch {
      const m = text.match(/(\d{1,3})/);
      probability = m ? Math.max(0, Math.min(100, parseInt(m[1], 10))) : 0;
    }

    const checkedAt = new Date().toISOString();
    await supabase.from("essays")
      .update({ ai_probability: probability, ai_checked_at: checkedAt })
      .eq("id", essay_id);

    return new Response(JSON.stringify({ probability, reasoning, ai_checked_at: checkedAt }), {
      status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("detect-ai error", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});