// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-essays.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-essays.ts
var list_essays_default = defineTool({
  name: "list_essays",
  title: "List essays",
  description: "List the signed-in student's essays with topic, subject, mode, word count, and submission status.",
  inputSchema: {
    mode: z.enum(["classroom", "solo", "brainstorm"]).optional().describe("Optional filter by writing mode."),
    submitted: z.boolean().optional().describe("Optional filter by submission status."),
    limit: z.number().int().optional().describe("Maximum number of essays to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ mode, submitted, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("essays").select("id, topic, subject, mode, is_submitted, content, updated_at, created_at").order("updated_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (mode) query = query.eq("mode", mode);
    if (typeof submitted === "boolean") query = query.eq("is_submitted", submitted);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const essays = (data ?? []).map((row) => ({
      id: row.id,
      topic: row.topic,
      subject: row.subject,
      mode: row.mode,
      submitted: row.is_submitted,
      word_count: String(row.content ?? "").trim().split(/\s+/).filter(Boolean).length,
      updated_at: row.updated_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(essays, null, 2) }],
      structuredContent: { essays }
    };
  }
});

// src/lib/mcp/tools/get-essay.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_essay_default = defineTool2({
  name: "get_essay",
  title: "Get essay",
  description: "Read one of the signed-in student's essays: full text, topic, subject, mode, status, and AI evaluation when available.",
  inputSchema: {
    essay_id: z2.string().describe("The essay id returned by list_essays.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ essay_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("essays").select(
      "id, topic, subject, mode, content, is_submitted, ai_evaluation, ai_feedback, topic_brief, created_at, updated_at"
    ).eq("id", essay_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Essay not found or not accessible." }], isError: true };
    }
    const essay = {
      ...data,
      word_count: String(data.content ?? "").trim().split(/\s+/).filter(Boolean).length
    };
    return {
      content: [{ type: "text", text: JSON.stringify(essay, null, 2) }],
      structuredContent: { essay }
    };
  }
});

// src/lib/mcp/tools/create-essay.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var create_essay_default = defineTool3({
  name: "create_essay",
  title: "Create practice essay",
  description: "Create a new personal practice essay (solo or brainstorm mode) for the signed-in student. Classroom essays must be started in the app with a lesson code.",
  inputSchema: {
    topic: z3.string().describe("Essay topic or prompt."),
    subject: z3.string().describe("Subject: English, Russian Literature, Kazakh Literature, or General."),
    mode: z3.enum(["solo", "brainstorm"]).optional().describe("Writing mode; defaults to solo practice."),
    duration_minutes: z3.number().int().optional().describe("Timer length for solo practice in minutes (default 45).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ topic, subject, mode, duration_minutes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const trimmedTopic = topic.trim();
    if (!trimmedTopic) {
      return { content: [{ type: "text", text: "Topic must not be empty." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("essays").insert({
      student_id: ctx.getUserId(),
      topic: trimmedTopic,
      subject: subject.trim() || "General",
      mode: mode ?? "solo",
      classroom_id: null,
      content: "",
      duration_minutes: mode === "brainstorm" ? null : Math.min(Math.max(duration_minutes ?? 45, 5), 180)
    }).select("id, topic, subject, mode").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [
        { type: "text", text: `Created essay ${data?.id} \u2014 open it in the app at /essay/${data?.id}` }
      ],
      structuredContent: { essay: data }
    };
  }
});

// src/lib/mcp/tools/save-draft.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.25.76";
var save_draft_default = defineTool4({
  name: "save_draft",
  title: "Save essay draft",
  description: "Replace the text of one of the signed-in student's own unsubmitted personal practice essays (solo or brainstorm). Classroom and submitted essays cannot be edited here.",
  inputSchema: {
    essay_id: z4.string().describe("The essay id returned by list_essays."),
    content: z4.string().describe("Full replacement draft text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ essay_id, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: essay, error: readError } = await supabase.from("essays").select("id, mode, is_submitted, classroom_id").eq("id", essay_id).maybeSingle();
    if (readError) return { content: [{ type: "text", text: readError.message }], isError: true };
    if (!essay) {
      return { content: [{ type: "text", text: "Essay not found or not accessible." }], isError: true };
    }
    if (essay.is_submitted) {
      return { content: [{ type: "text", text: "This essay is submitted and locked." }], isError: true };
    }
    if (essay.classroom_id || essay.mode === "classroom") {
      return {
        content: [{ type: "text", text: "Classroom essays can only be edited in the app's writing environment." }],
        isError: true
      };
    }
    const { error } = await supabase.from("essays").update({ content, updated_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", essay_id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const words = content.trim().split(/\s+/).filter(Boolean).length;
    return {
      content: [{ type: "text", text: `Draft saved (${words} words).` }],
      structuredContent: { essay_id, word_count: words }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xwbwvdvyetitdudjctum";
var mcp_default = defineMcp({
  name: "oilan-ai",
  title: "Oilan AI",
  version: "0.1.0",
  instructions: "Tools for Oilan AI, a Socratic writing platform for high school students. Use `list_essays` and `get_essay` to read the signed-in student's essays, `create_essay` to start a personal practice essay, and `save_draft` to update an unsubmitted personal draft. Classroom essays are read-only here; they must be written in the app's locked writing environment. Never write essay text on the student's behalf unless they explicitly ask for their own drafted text to be saved.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_essays_default, get_essay_default, create_essay_default, save_draft_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
